name: Build and Deploy Jekyll Site from /docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Install dependencies and build site
        uses: limjh16/jekyll-action-ts@v2
        env:
          NODE_ENV: "production"
        with:
          enable_cache: true
          base_path: ./docs  # this tells jekyll-action-ts to use /docs as the site root

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
